### ISSUE TITLE
Can nest blocks into sensor port number. 

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-blocks#18]
Can nest blocks into sensor port number. Is there any reason you would want to do this? Most output values are not valid.

**Comment by jenncross** [comment]
I could see a advanced use case with looping through the sensors in a for loop .... but I highly doubt this will come up for this age group. It is more important to help with error prevention for these novice users.

**Comment by jenncross** [comment]
Related to #19  and #33, probably even a duplicate.
